//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DesktopIconAssistant.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DESKTOPICONASSISTANT_DIALOG 102
#define IDS_FAIL_INIT                   102
#define IDS_ERROR                       103
#define IDS_APP_NAME                    104
#define IDS_TIP_CLOSE                   105
#define IDS_TIP_MIN                     106
#define IDS_TIP_UNDO                    107
#define IDS_TIP_REDO                    108
#define IDS_TIP_EXCHANGE                109
#define IDS_TIP_HIDE                    110
#define IDS_ALERT                       111
#define IDS_TIP_LEFT                    112
#define IDS_TIP_RIGHT                   113
#define IDS_TIP_UP                      114
#define IDS_TIP_DOWN                    115
#define IDS_TIP_HEART                   116
#define IDS_TIP_OVAL                    117
#define IDS_TIP_FILLRECT                118
#define IDS_TIP_HOLLOWRECT              119
#define IDS_TIP_LINE                    120
#define IDS_TIP_BIG                     121
#define IDS_TIP_MID                     122
#define IDS_TIP_SMALL                   123
#define IDS_TIP_AUTO                    124
#define IDS_TIP_CUSTOM                  125
#define IDS_TIP_SAVE                    126
#define IDS_TIP_LOAD                    127
#define IDR_MAINFRAME                   128
#define IDS_FIX_ICON                    128
#define IDB_BG                          129
#define IDS_ICON_FIXED                  129
#define IDS_CANNOT_UNDO                 130
#define IDS_CANNOT_REDO                 131
#define IDB_SYSTEM_DOWN                 132
#define IDS_SAVED                       132
#define IDB_SYSTEM_NORMAL               133
#define IDS_LOADED                      133
#define IDB_SYSTEM_OVER                 134
#define IDS_SELECT_TWO_ICONS            134
#define IDB_RIGHT_NORMAL                135
#define IDS_TIP_SHOW                    135
#define IDB_LEFT_NORMAL                 136
#define IDS_ICON_SELECTED               136
#define IDS_ICONS_SELECTED              136
#define IDB_DOWN_NORMAL                 137
#define IDS_STRING137                   137
#define IDB_DOWN_OVER                   138
#define IDS_TIP_BEZIER                  138
#define IDB_LEFT_OVER                   139
#define IDB_RIGHT_OVER                  140
#define IDB_UP_NORMAL                   141
#define IDB_UP_OVER                     142
#define IDB_HEART_OVER                  143
#define IDB_HEART_NORMAL                144
#define IDB_OVAL_OVER                   145
#define IDB_OVAL_NORMAL                 146
#define IDB_HOLLOWRECT_OVER             147
#define IDB_FILLRECT_NORMAL             148
#define IDB_FILLRECT_OVER               149
#define IDB_HOLLOWRECT_NORMAL           150
#define IDB_LINE_NORMAL                 151
#define IDB_LINE_OVER                   152
#define IDB_AUTO_OVER                   153
#define IDB_BIG_NORMAL                  154
#define IDB_BIG_OVER                    155
#define IDB_CUSTOM_NORMAL               156
#define IDB_CUSTOM_OVER                 157
#define IDB_MID_NORMAL                  158
#define IDB_MID_OVER                    159
#define IDB_SMALL_NORMAL                160
#define IDB_SMALL_OVER                  161
#define IDB_AUTO_NORMAL                 162
#define IDB_SMALL_DOWN                  163
#define IDB_BIG_DOWN                    164
#define IDB_MID_DOWN                    165
#define IDB_CUSTOM_DOWN                 166
#define IDB_AUTO_DOWN                   167
#define IDD_DESKTOP                     171
#define IDB_DESKTOP_BG                  172
#define IDB_CANCEL_NORMAL               173
#define IDB_CANCEL_OVER                 174
#define IDB_OK_NORMAL                   175
#define IDB_OK_OVER                     176
#define IDB_LOAD_NORMAL                 177
#define IDB_LOAD_OVER                   178
#define IDB_SAVE_NORMAL                 179
#define IDB_SAVE_OVER                   180
#define IDR_MENU_POPUP                  181
#define IDB_BEZIER_NORMAL               184
#define IDB_BITMAP2                     185
#define IDB_BEZIER_OVER                 185
#define IDC_BUTTON_MIN                  1001
#define IDC_BUTTON_CLOSE                1002
#define IDC_BUTTON_LEFT                 1003
#define IDC_BUTTON_RIGHT                1004
#define IDC_BUTTON_DOWN                 1005
#define IDC_BUTTON_UP                   1006
#define IDC_BUTTON_HEART                1007
#define IDC_BUTTON_OVAL                 1008
#define IDC_BUTTON_HOLLOW_RECT          1009
#define IDC_BUTTON_FILL_RECT            1010
#define IDC_BUTTON_LINE                 1011
#define IDC_BUTTON_BIG                  1016
#define IDC_BUTTON_MID                  1017
#define IDC_BUTTON_SMALL                1018
#define IDC_BUTTON_AUTO                 1019
#define IDC_BUTTON_CUSTOM               1020
#define IDC_EDIT_SPACE                  1022
#define IDC_BUTTON_REDO                 1023
#define IDC_BUTTON_UNDO                 1024
#define IDC_BUTTON_SAVE                 1026
#define IDC_BUTTON_LOAD                 1027
#define IDC_BUTTON_EXCHANGE             1028
#define IDC_BUTTON_HIDE_TEXT            1029
#define IDC_BUTTON_BEZIER               1032
#define ID_POPUP_32771                  32771
#define ID_POPUP_32772                  32772
#define ID_32773                        32773
#define ID_32774                        32774
#define ID_32775                        32775
#define ID_32776                        32776
#define ID_POPUP_                       32777
#define ID_POPUP_32778                  32778
#define ID_POPUP_32779                  32779
#define ID_POPUP_32780                  32780
#define ID_POPUP_32781                  32781
#define ID_POPUP_32782                  32782
#define ID_Menu                         32783
#define ID_POPUP_32784                  32784
#define ID_POPUP_32785                  32785
#define ID_POPUP_32786                  32786
#define ID_POPUP_32787                  32787
#define ID_POPUP_SHOW                   32788
#define ID_ALIGN_LEFT                   32789
#define ID_ALIGN_RIGHT                  32790
#define ID_ALIGN_UP                     32791
#define ID_ALIGN_DOWN                   32792
#define ID_LINE                         32793
#define ID_RECT                         32794
#define ID_FILLRECT                     32795
#define ID_HOLLOWRECT                   32796
#define ID_OVAL                         32797
#define ID_HEART                        32798
#define ID_UNDO                         32799
#define ID_REDO                         32800
#define ID_SAVE                         32801
#define ID_LOAD                         32802
#define ID_EXIT                         32803
#define ID_POPUP_32804                  32804
#define ID_Menu32805                    32805
#define ID_32806                        32806
#define ID_32807                        32807
#define ID_32808                        32808
#define ID_32809                        32809
#define ID_SPACE_AUTO                   32810
#define ID_SPACE_BIG                    32811
#define ID_SPACE_MID                    32812
#define ID_SPACE_SMALL                  32813
#define ID_32814                        32814
#define ID_CUSTOM                       32815
#define ID_SPACE_CUSTOM                 32816
#define ID_POPUP_32817                  32817
#define ID_ABOUT                        32818
#define ID_Menu32819                    32819
#define ID_EXCHANGE                     32820
#define ID_Menu32821                    32821
#define ID_32822                        32822
#define ID_HIDE_TEXT                    32823
#define ID_Menu32825                    32825
#define ID_BEZIER                       32826

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        186
#define _APS_NEXT_COMMAND_VALUE         32827
#define _APS_NEXT_CONTROL_VALUE         1033
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
